//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 01:54:48 PM BRT 
//


package modul2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Flower" maxOccurs="10">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Soil">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="�����������"/>
 *                         &lt;enumeration value="���������"/>
 *                         &lt;enumeration value="�������-�����������"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Visualparameters">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Stalkcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Growingtips">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Temp" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="Water" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="Multiplying">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="���������|��������"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flower"
})
@XmlRootElement(name = "Flowers")
    public class Flowers {

        @XmlElement(name = "Name", required = true)
        protected static String name;
        @XmlElement(name = "Soil", required = true)
        protected String soil;
        @XmlElement(name = "Origin", required = true)
        protected String origin;
        @XmlElement(name = "Visualparameters", required = true)
        protected Flowers.Visualparameters visualparameters;
        @XmlElement(name = "Growingtips", required = true)
        protected Flowers.Growingtips growingtips;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name + " " + soil + " " + origin;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the soil property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSoil() {
            return soil;
        }

        /**
         * Sets the value of the soil property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSoil(String value) {
            this.soil = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the visualparameters property.
         * 
         * @return
         *     possible object is
         *     {@link Flowers.Flower.Visualparameters }
         *     
         */
        public Flowers.Visualparameters getVisualparameters() {
            return visualparameters;
        }

        /**
         * Sets the value of the visualparameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Flowers.Flower.Visualparameters }
         *     
         */
        public void setVisualparameters(Flowers.Visualparameters value) {
            this.visualparameters = value;
        }

        /**
         * Gets the value of the growingtips property.
         * 
         * @return
         *     possible object is
         *     {@link Flowers.Flower.Growingtips }
         *     
         */
        public Flowers.Growingtips getGrowingtips() {
            return growingtips;
        }

        /**
         * Sets the value of the growingtips property.
         * 
         * @param value
         *     allowed object is
         *     {@link Flowers.Flower.Growingtips }
         *     
         */
        public void setGrowingtips(Flowers.Growingtips value) {
            this.growingtips = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Temp" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="Water" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="Multiplying">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="���������|��������"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "temp",
            "water",
            "multiplying"
        })
        public static class Growingtips {

            @XmlElement(name = "Temp")
            protected short temp;
            @XmlElement(name = "Water")
            protected short water;
            @XmlElement(name = "Multiplying", required = true)
            protected String multiplying;

            /**
             * Gets the value of the temp property.
             * 
             */
            public short getTemp() {
                return temp;
            }

            /**
             * Sets the value of the temp property.
             * 
             */
            public void setTemp(short value) {
                this.temp = value;
            }

            /**
             * Gets the value of the water property.
             * 
             */
            public short getWater() {
                return water;
            }

            /**
             * Sets the value of the water property.
             * 
             */
            public void setWater(short value) {
                this.water = value;
            }

            /**
             * Gets the value of the multiplying property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMultiplying() {
                return multiplying;
            }
            
            public String toString(){
            	return name;
            }

            /**
             * Sets the value of the multiplying property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMultiplying(String value) {
                this.multiplying = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Stalkcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stalkcolor",
            "size"
        })
        public static class Visualparameters {

            @XmlElement(name = "Stalkcolor", required = true)
            protected String stalkcolor;
            @XmlElement(name = "Size", required = true)
            protected String size;

            /**
             * Gets the value of the stalkcolor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStalkcolor() {
                return stalkcolor;
            }

            /**
             * Sets the value of the stalkcolor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStalkcolor(String value) {
                this.stalkcolor = value;
            }

            /**
             * Gets the value of the size property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSize() {
                return size;
            }

            /**
             * Sets the value of the size property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSize(String value) {
                this.size = value;
            }

        }

    }
